namespace Outbox.Relay.Endpoints;

public static class InstallerScript
{
    public static string Generate(string relayUrl, string? inviteCode, string repoUrl)
    {
        return Template
            .Replace("__RELAY_URL__", relayUrl)
            .Replace("__INVITE_CODE__", inviteCode ?? "")
            .Replace("__REPO_URL__", repoUrl);
    }

    private const string Template = """
        #!/usr/bin/env bash
        # Outbox installer — generated by the relay
        set -euo pipefail

        RELAY_URL="__RELAY_URL__"
        INVITE_CODE="__INVITE_CODE__"
        REPO_URL="${OUTBOX_REPO_URL:-__REPO_URL__}"
        INSTALL_DIR="${OUTBOX_INSTALL_DIR:-$HOME/.outbox/app}"
        BIN_DIR="${OUTBOX_BIN_DIR:-$HOME/.local/bin}"

        bold() { printf '\033[1m%s\033[0m\n' "$*"; }
        warn() { printf '\033[33m%s\033[0m\n' "$*"; }
        err()  { printf '\033[31mError: %s\033[0m\n' "$*" >&2; exit 1; }

        bold "→ Outbox installer"
        echo "   Relay: $RELAY_URL"
        [ -n "$INVITE_CODE" ] && echo "   Invite: ${INVITE_CODE:0:4}…"
        echo

        # Prereqs
        command -v node >/dev/null 2>&1 || err "node not found. Install Node.js 20+ first."
        NODE_MAJOR=$(node -e 'process.stdout.write(process.versions.node.split(".")[0])')
        if [ "$NODE_MAJOR" -lt 20 ]; then err "node $NODE_MAJOR is too old. Need 20+."; fi
        command -v npm >/dev/null 2>&1 || err "npm not found."
        command -v git >/dev/null 2>&1 || err "git not found."

        # Clone or update source
        mkdir -p "$(dirname "$INSTALL_DIR")"
        if [ -d "$INSTALL_DIR/.git" ]; then
          bold "→ Updating $INSTALL_DIR"
          git -C "$INSTALL_DIR" fetch --depth 1 origin main >/dev/null
          git -C "$INSTALL_DIR" reset --hard origin/main >/dev/null
        else
          bold "→ Cloning $REPO_URL → $INSTALL_DIR"
          git clone --depth 1 "$REPO_URL" "$INSTALL_DIR"
        fi

        # Build the MCP package
        bold "→ Installing dependencies"
        cd "$INSTALL_DIR/mcp"
        npm install --silent --no-audit --no-fund
        bold "→ Building"
        npm run build --silent

        # Link bins
        mkdir -p "$BIN_DIR"
        ln -sf "$INSTALL_DIR/mcp/dist/index.js" "$BIN_DIR/outbox-mcp"
        ln -sf "$INSTALL_DIR/mcp/dist/cli.js"   "$BIN_DIR/outbox"
        chmod +x "$INSTALL_DIR/mcp/dist/index.js" "$INSTALL_DIR/mcp/dist/cli.js"
        bold "→ Linked outbox + outbox-mcp into $BIN_DIR"

        case ":$PATH:" in
          *":$BIN_DIR:"*) ;;
          *)
            echo
            warn "$BIN_DIR is not on your PATH."
            echo   "Add it (then \`source\` your rc file):"
            echo   "    echo 'export PATH=\"$BIN_DIR:\$PATH\"' >> ~/.zshrc   # or ~/.bashrc"
            ;;
        esac

        # Setup
        echo
        if [ -n "$INVITE_CODE" ]; then
          bold "→ Redeeming invite"
          "$BIN_DIR/outbox" setup --relay-url "$RELAY_URL" --invite "$INVITE_CODE"
        else
          bold "→ Interactive setup"
          "$BIN_DIR/outbox" setup --relay-url "$RELAY_URL"
        fi

        echo
        bold "✓ Done."
        echo "  Restart Claude Code to load the outbox MCP server."
        echo "  Try: /inbox  (or wait for a SessionStart notification when someone sends you a message)"
        """;
}
